from __future__ import annotations

# Pipeline progress steps
PIPELINE_PROGRESS_VALIDATE_INPUT = 5
PIPELINE_PROGRESS_CHECK_AUDIO = 15
PIPELINE_PROGRESS_EXTRACT_AUDIO = 30
PIPELINE_PROGRESS_PREPARE_STT = 45
PIPELINE_PROGRESS_PREPARE_DIARIZATION = 50
PIPELINE_PROGRESS_DONE = 100

# STT progress tuning
STT_PROGRESS_UPDATE_EVERY_SEGMENTS = 10
STT_PROGRESS_TRANSCRIBING = 55
STT_PROGRESS_TRANSCRIBE_DONE = 70

# 화자 역할 미리보기(멘토 지정 UX)
SPEAKER_PREVIEW_MIN_CHARS = 12
SPEAKER_PREVIEW_MAX_QUOTES = 6
SPEAKER_DEFAULT_TRAINEE_LABEL = "교육생"
SPEAKER_MAP_OTHERS_TO_TRAINEE_DEFAULT = True
